version: "3.9"

services:
  modbus-garagedoor-webhook:
    build: .
    container_name: modbus-webhook
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production