version: "3.9"

services:
  modbus-garagedoor-webhook:
    build: .
    container_name: modbus-garagedoor-webhook
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: production
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true