apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-bell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-bell
  template:
    metadata:
      labels:
        app: webhook-bell
    spec:
      containers:
        - name: webhook-bell
          image: ghcr.io/dein-user/webhook-bell:1.0.3
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-bell
spec:
  selector:
    app: webhook-bell
  ports:
    - port: 80
      targetPort: 8080
